version: '3.8'

services:
  product-service:
    build: ./product-service
    ports:
      - "5000:5000"
    networks:
      - shopping-network

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    networks:
      - shopping-network

  cart-service:
    build: ./cart-service
    ports:
      - "5002:5002"
    networks:
      - shopping-network

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    networks:
      - shopping-network

  payment-service:
    build: ./payment-service
    ports:
      - "5004:5004"
    networks:
      - shopping-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - shopping-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shopping-network

networks:
  shopping-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: